/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReflectionsIndexRouteImport } from './routes/reflections.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as ReflectionsSlugRouteImport } from './routes/reflections.$slug'
import { Route as ReaderBookIdRouteImport } from './routes/reader.$bookId'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiPdfRouteImport } from './routes/api/pdf'
import { Route as ApiLogErrorRouteImport } from './routes/api/log-error'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as NewsletterUnsubscribeTokenRouteImport } from './routes/newsletter.unsubscribe.$token'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsIndexRoute = ReflectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReflectionsRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const ReflectionsSlugRoute = ReflectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReflectionsRoute,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BooksRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogErrorRoute = ApiLogErrorRouteImport.update({
  id: '/api/log-error',
  path: '/api/log-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribeTokenRoute =
  NewsletterUnsubscribeTokenRouteImport.update({
    id: '/newsletter/unsubscribe/$token',
    path: '/newsletter/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/bookmarks': typeof BookmarksRoute
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reflections': typeof ReflectionsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reflections/$slug': typeof ReflectionsSlugRoute
  '/books/': typeof BooksIndexRoute
  '/reflections/': typeof ReflectionsIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/bookmarks': typeof BookmarksRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reflections/$slug': typeof ReflectionsSlugRoute
  '/books': typeof BooksIndexRoute
  '/reflections': typeof ReflectionsIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/bookmarks': typeof BookmarksRoute
  '/books': typeof BooksRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reflections': typeof ReflectionsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/videos': typeof VideosRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/log-error': typeof ApiLogErrorRoute
  '/api/pdf': typeof ApiPdfRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/reflections/$slug': typeof ReflectionsSlugRoute
  '/books/': typeof BooksIndexRoute
  '/reflections/': typeof ReflectionsIndexRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/newsletter/unsubscribe/$token': typeof NewsletterUnsubscribeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/books'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/reflections'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/videos'
    | '/wishlist'
    | '/api/chat'
    | '/api/log-error'
    | '/api/pdf'
    | '/api/stripe-webhook'
    | '/books/$slug'
    | '/checkout/success'
    | '/pages/$slug'
    | '/posts/$slug'
    | '/reader/$bookId'
    | '/reflections/$slug'
    | '/books/'
    | '/reflections/'
    | '/api/payments/webhook'
    | '/newsletter/unsubscribe/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/videos'
    | '/wishlist'
    | '/api/chat'
    | '/api/log-error'
    | '/api/pdf'
    | '/api/stripe-webhook'
    | '/books/$slug'
    | '/checkout/success'
    | '/pages/$slug'
    | '/posts/$slug'
    | '/reader/$bookId'
    | '/reflections/$slug'
    | '/books'
    | '/reflections'
    | '/api/payments/webhook'
    | '/newsletter/unsubscribe/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/books'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/orders'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/reflections'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/videos'
    | '/wishlist'
    | '/api/chat'
    | '/api/log-error'
    | '/api/pdf'
    | '/api/stripe-webhook'
    | '/books/$slug'
    | '/checkout/success'
    | '/pages/$slug'
    | '/posts/$slug'
    | '/reader/$bookId'
    | '/reflections/$slug'
    | '/books/'
    | '/reflections/'
    | '/api/payments/webhook'
    | '/newsletter/unsubscribe/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  BookmarksRoute: typeof BookmarksRoute
  BooksRoute: typeof BooksRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  ReflectionsRoute: typeof ReflectionsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  VideosRoute: typeof VideosRoute
  WishlistRoute: typeof WishlistRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiLogErrorRoute: typeof ApiLogErrorRoute
  ApiPdfRoute: typeof ApiPdfRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  NewsletterUnsubscribeTokenRoute: typeof NewsletterUnsubscribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections/': {
      id: '/reflections/'
      path: '/'
      fullPath: '/reflections/'
      preLoaderRoute: typeof ReflectionsIndexRouteImport
      parentRoute: typeof ReflectionsRoute
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/reflections/$slug': {
      id: '/reflections/$slug'
      path: '/$slug'
      fullPath: '/reflections/$slug'
      preLoaderRoute: typeof ReflectionsSlugRouteImport
      parentRoute: typeof ReflectionsRoute
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof BooksRoute
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log-error': {
      id: '/api/log-error'
      path: '/api/log-error'
      fullPath: '/api/log-error'
      preLoaderRoute: typeof ApiLogErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribe/$token': {
      id: '/newsletter/unsubscribe/$token'
      path: '/newsletter/unsubscribe/$token'
      fullPath: '/newsletter/unsubscribe/$token'
      preLoaderRoute: typeof NewsletterUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksSlugRoute: typeof BooksSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksSlugRoute: BooksSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ReflectionsRouteChildren {
  ReflectionsSlugRoute: typeof ReflectionsSlugRoute
  ReflectionsIndexRoute: typeof ReflectionsIndexRoute
}

const ReflectionsRouteChildren: ReflectionsRouteChildren = {
  ReflectionsSlugRoute: ReflectionsSlugRoute,
  ReflectionsIndexRoute: ReflectionsIndexRoute,
}

const ReflectionsRouteWithChildren = ReflectionsRoute._addFileChildren(
  ReflectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  BookmarksRoute: BookmarksRoute,
  BooksRoute: BooksRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  ReflectionsRoute: ReflectionsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  VideosRoute: VideosRoute,
  WishlistRoute: WishlistRoute,
  ApiChatRoute: ApiChatRoute,
  ApiLogErrorRoute: ApiLogErrorRoute,
  ApiPdfRoute: ApiPdfRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PagesSlugRoute: PagesSlugRoute,
  PostsSlugRoute: PostsSlugRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  NewsletterUnsubscribeTokenRoute: NewsletterUnsubscribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
